/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author kms03
 */
public class AdminUser extends javax.swing.JPanel {

    DB_MAN DBM = new DB_MAN();
    /**
     * Creates new form AdminUser
     */
    public AdminUser() {
        initComponents();
        loadUserList(); // 켜자마자 목록 로딩
    }
    
    public void loadUserList() {
        String type = cboType.getSelectedItem().toString();
        String strSQL = "";
        
        // 선택된 타입에 따라 쿼리 변경
        if (type.equals("학생")) {
            strSQL = "SELECT stu_id, name, dept, password FROM Student";
        } else {
            strSQL = "SELECT prof_id, name, dept, password FROM Professor";
        }

        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            model.setRowCount(0);
            
            while(DBM.DB_rs.next()) {
                Vector v = new Vector();
                // 첫 번째 컬럼(ID)이 학생이면 stu_id, 교수면 prof_id
                v.add(DBM.DB_rs.getString(1)); 
                v.add(DBM.DB_rs.getString("name"));
                v.add(DBM.DB_rs.getString("dept"));
                v.add(DBM.DB_rs.getString("password"));
                model.addRow(v);
            }
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("목록 로드 에러: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboType = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "학생", "교수" }));

        btnSearch.setText("조회");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "아이디", "이름", "학과", "비밀번호"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnDelete.setText("삭제");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadUserList();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "삭제할 사용자를 선택하세요.");
            return;
        }
        
        // 선택된 ID 가져오기
        String selectedID = tblUsers.getValueAt(selectedRow, 0).toString();
        String type = cboType.getSelectedItem().toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "선택한 사용자(" + selectedID + ")를 정말 삭제하시겠습니까?\n관련된 모든 데이터(성적, 강의 등)가 함께 삭제됩니다.", 
                "삭제 확인", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) return;

        String strSQL = "";
        if (type.equals("학생")) {
            strSQL = "DELETE FROM Student WHERE stu_id = '" + selectedID + "'";
        } else {
            strSQL = "DELETE FROM Professor WHERE prof_id = '" + selectedID + "'";
        }

        try {
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
            
            JOptionPane.showMessageDialog(this, "삭제되었습니다.");
            loadUserList(); // 목록 갱신
            
        } catch (Exception e) {
            System.out.println("삭제 에러: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "삭제 실패: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
