/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author kms03
 */
public class ProfessorGradeForm extends javax.swing.JPanel {

    DB_MAN DBM = new DB_MAN();
    String myID; // 로그인한 교수님 교번
    String selectedEnrollID;
    
    /**
     * Creates new form ProfessorGrade
     */
    public ProfessorGradeForm() {
        initComponents();
    }
    
    public ProfessorGradeForm(String id) {
        initComponents();
        this.myID = id;
        loadCourseList();
    }
    
    public void loadCourseList() {
        try {
            String strSQL = "SELECT lecture_id, title FROM Lecture WHERE prof_id = '" + myID + "'";
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            
            cboLecture.removeAllItems(); // 기존 목록 비우기
            while (DBM.DB_rs.next()) {
                // 콤보박스에 "강의명(강의코드)" 형태로 넣기
                String item = DBM.DB_rs.getString("title") + "(" + DBM.DB_rs.getString("lecture_id") + ")";
                cboLecture.addItem(item);
            }
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("강의 목록 로드 에러: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboLecture = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtScore = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();

        jLabel1.setText("강의 선택");

        cboLecture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSearch.setText("조회");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "순번", "학번", "이름", "점수", "학점"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        jLabel2.setText("점수");

        jLabel3.setText("학점");

        btnUpdate.setText("점수 수정");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cboLecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate)
                                .addGap(60, 60, 60)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String selectedItem = cboLecture.getSelectedItem().toString();
        // "자바(CS101)" 에서 괄호 안의 "CS101"만 추출하기
        String lectureID = selectedItem.substring(selectedItem.indexOf("(") + 1, selectedItem.indexOf(")"));

        try {
            // 수강신청(E) 테이블과 학생(S) 테이블 조인
            String strSQL = "SELECT E.enroll_id, S.stu_id, S.name, E.score, E.grade "
                          + "FROM Enrollment E "
                          + "JOIN Student S ON E.stu_id = S.stu_id "
                          + "WHERE E.lecture_id = '" + lectureID + "'";
            
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            
            DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
            model.setRowCount(0);
            
            while(DBM.DB_rs.next()) {
                Vector v = new Vector();
                v.add(DBM.DB_rs.getInt("enroll_id")); // 수정 기준 키 (숨겨도 됨)
                v.add(DBM.DB_rs.getString("stu_id"));
                v.add(DBM.DB_rs.getString("name"));
                v.add(DBM.DB_rs.getInt("score"));
                v.add(DBM.DB_rs.getString("grade"));
                model.addRow(v);
            }
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("수강생 조회 에러: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        int selectedRow = tblStudents.getSelectedRow();
        // 선택한 줄의 데이터 가져오기
        selectedEnrollID = tblStudents.getValueAt(selectedRow, 0).toString(); // 고유번호 저장
        txtScore.setText(tblStudents.getValueAt(selectedRow, 3).toString());
        
        // 등급이 null일 수 있으므로 체크
        Object gradeObj = tblStudents.getValueAt(selectedRow, 4);
        if(gradeObj != null) txtGrade.setText(gradeObj.toString());
        else txtGrade.setText("");
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedEnrollID == null) {
            JOptionPane.showMessageDialog(this, "학생을 선택해주세요.");
            return;
        }
        
        String score = txtScore.getText();
        String grade = txtGrade.getText();
        
        // 점수 업데이트 쿼리
        String strSQL = "UPDATE Enrollment SET score = " + score + ", grade = '" + grade + "' "
                      + "WHERE enroll_id = " + selectedEnrollID;
        
        try {
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
            
            JOptionPane.showMessageDialog(this, "성적 입력 완료!");
            btnSearch.doClick(); // 목록 새로고침 (자동 클릭 효과)
            
        } catch (Exception e) {
            System.out.println("업데이트 에러: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboLecture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
