/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kms03
 */
public class StudentGradeForm extends javax.swing.JPanel {

    DB_MAN DBM = new DB_MAN();
    String myID;
    
    public StudentGradeForm() {
        initComponents();
    }
    
    public StudentGradeForm(String id) {
        initComponents();
        this.myID = id;
        getGradeList(); // 켜자마자 성적 조회 실행
    }
    
    public void getGradeList() {
        try {
            // ★ 핵심 쿼리: 수강신청(E) 테이블과 강의(L) 테이블을 합침(JOIN)
            // 이유는? 수강신청 테이블엔 '강의코드'만 있고 '강의명'이 없으니까!
            String strSQL = "SELECT L.title, L.prof_id, L.credit, E.score, E.grade "
                          + "FROM Enrollment E "
                          + "JOIN Lecture L ON E.lecture_id = L.lecture_id "
                          + "WHERE E.stu_id = '" + myID + "'";

            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);

            DefaultTableModel model = (DefaultTableModel) tblGrade.getModel();
            model.setRowCount(0); // 초기화

            while (DBM.DB_rs.next()) {
                Vector v = new Vector();
                v.add(DBM.DB_rs.getString("title"));   // 강의명 (Lecture 테이블)
                v.add(DBM.DB_rs.getString("prof_id")); // 교수님 (Lecture 테이블)
                v.add(DBM.DB_rs.getInt("credit"));     // 학점 (Lecture 테이블)
                v.add(DBM.DB_rs.getInt("score"));      // 점수 (Enrollment 테이블)
                v.add(DBM.DB_rs.getString("grade"));   // 등급 (Enrollment 테이블)
                model.addRow(v);
            }
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("성적 조회 에러: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        tblGrade = new javax.swing.JTable();

        tblGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "강의명", "담당교수", "학점", "점수", "등급"
            }
        ));
        jScrollPane.setViewportView(tblGrade);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable tblGrade;
    // End of variables declaration//GEN-END:variables
}
