/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kms03
 */
public class StudentEnrollForm extends javax.swing.JPanel {

    DB_MAN DBM = new DB_MAN(); 
    String myID; 

    /**
     * Creates new form StudentEnroll
     */
    public StudentEnrollForm() {
        initComponents();
    }
    
    public StudentEnrollForm(String id) {
        initComponents();
        this.myID = id;
        getLectureList(); 
    }
    
    public void getLectureList() {
        try {
            String strSQL = "SELECT * FROM Lecture";
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);

            // JTable 모델 가져오기
            DefaultTableModel model = (DefaultTableModel) tblLecture.getModel();
            model.setRowCount(0); // 기존 데이터 싹 지우기 (초기화)

            while (DBM.DB_rs.next()) {
                Vector v = new Vector();
                v.add(DBM.DB_rs.getString("lecture_id"));
                v.add(DBM.DB_rs.getString("title"));
                v.add(DBM.DB_rs.getInt("credit"));
                v.add(DBM.DB_rs.getString("prof_id"));
                v.add(DBM.DB_rs.getString("room"));
                v.add(DBM.DB_rs.getInt("max_student"));
                model.addRow(v); // 한 줄 추가
            }
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("강의 목록 로드 에러: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLecture = new javax.swing.JTable();
        btnRegister = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        tblLecture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLecture);

        btnRegister.setText("수강신청");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnRefresh.setText("조회");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnRefresh)
                        .addGap(71, 71, 71)
                        .addComponent(btnRegister)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        int selectedRow = tblLecture.getSelectedRow();
        
        if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "신청할 강의를 선택해주세요!");
        return; // 함수 종료
    }
        
        String selectedCourseID = tblLecture.getValueAt(selectedRow, 0).toString();
        String selectedTitle = tblLecture.getValueAt(selectedRow, 1).toString();
        
        String strSQL = "INSERT INTO Enrollment (stu_id, lecture_id, score, grade) VALUES ('" 
            + myID + "', '" + selectedCourseID + "', 0, null)";
        
        try {
        DBM.dbOpen();
        DBM.DB_stmt.executeUpdate(strSQL); // Insert 실행
        DBM.dbClose();
        
        // 성공 메시지
        javax.swing.JOptionPane.showMessageDialog(this, selectedTitle + " 강의 신청 완료!");
        
        } catch (Exception e) {
            System.out.println("신청 에러: " + e.getMessage());
            // 이미 신청한 강의를 또 누르면 에러가 날 수 있습니다 (PK/Unique 설정 시)
            javax.swing.JOptionPane.showMessageDialog(this, "수강신청 실패! (이미 신청했거나 오류 발생)");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLecture;
    // End of variables declaration//GEN-END:variables
}
